-- =======================================================================================
-- TAHAP 1.3.1: SETUP SQL UNTUK THE ULTIMATE RAG PIPELINE
-- =======================================================================================

-- 1. BIKIN TABEL BUKU INDUK DOKUMEN
-- Tabel ini menyimpan daftar dokumen yang pernah di-upload oleh Admin.
CREATE TABLE knowledge_dokumen (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama_dokumen TEXT NOT NULL,
    file_url TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. BIKIN TABEL GUDANG CHUNKING (ANTI-OOM)
-- Tabel ini menyimpan potongan teks dan Dense Vector-nya.
-- Kita menggunakan JSONB untuk menyimpan array float dari Gemini karena sangat ringan dan efisien.
CREATE TABLE knowledge_chunks (
    id TEXT PRIMARY KEY, -- Menggunakan MD5 Hash dari Kategori sebagai ID
    id_dokumen BIGINT REFERENCES knowledge_dokumen(id) ON DELETE CASCADE,
    kategori TEXT NOT NULL,
    teks TEXT NOT NULL,
    dense_vector JSONB NOT NULL
);

-- Keterangan: 'ON DELETE CASCADE' artinya kalau Admin menghapus dokumen dari tabel 'knowledge_dokumen',
-- maka ribuan chunk miliknya di tabel 'knowledge_chunks' akan otomatis terhapus tanpa sisa!
